Update where_i_left_off
syntax changes.

Need to correct compilation error with all integer declarations

Error (10477): VHDL error at test13.vhd(297): name "getting_display_ready" must represent signal